### ISSUE TITLE
Couple of ideas for you

### ISSUE THREAD

**Issue by danielbprice** [vaelen/iot#1]
As I mentioned, this is really nice!  I've written my own but I spent a lot of my time working around the password problem (I guess I should have forked the code, as you did); there are a lot of nice details in your code.

Some ideas if you are interested:
- I made the top-level client an interface, to facilitate mocking.
- I have a utility function which sets mqtt.DEBUG, mqtt.WARN, ... etc so that if you need it you can get the underlying MQTT debug information.
- I opted for now to expose the MQTT token to callers, because I wasn't sure if a fixed timeout would be the right thing.  Dunno if that's really a good idea or not.  I guess I could wrap the token to make it less ugly.

Anyway, well done.

**Comment by vaelen** [comment]
Thanks! I appreciate the feedback. :)  I'll integrate your suggestions this week.

**Comment by vaelen** [comment]
I've implemented most of your suggestions, please take a look and let me know what you think.

**Comment by vaelen** [comment]
I think I'll try to implement methods that use contexts instead of returning the MQTT tokens directly so that I can insulate the API from the underlying MQTT implementation.

**Comment by vaelen** [comment]
@danielbprice : I redid the API using Contexts.  I still need to add checking for deadlines, timeouts, etc, in the code but once that is done it will allow folks to timeout their MQTT calls.  I also abstracted away all of the MQTT code so that other clients can be used if necessary.

**Comment by vaelen** [comment]
Ok, I've added the context handling to allow the user to timeout or cancel blocked requests.  This should fulfill all of your needs.  Please let me know if I've missed anything.

**Comment by vaelen** [comment]
I'm going to close this for now.  Please let me know if there's anything else you need. :)
